name=SimpleBleSerial
version=1.0.0
author=OneDevelopmentPL
maintainer=OneDevelopmentPL
sentence=A Simple BLE Serial wrapper for ESP32 utilizing the Nordic UART Service.
paragraph=Provides an easy-to-use API similar to SoftwareSerial for Bluetooth Low Energy communication with phones and other devices. Includes extra features like RSSI checking, battery service, and chunking.
category=Communication
url=https://github.com/OneDevelopmentPL/SimpleBleSerial
architectures=esp32
includes=SimpleBleSerial.h
